// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webOkClass.DataContext;

namespace webOkClass.Migrations
{
    [DbContext(typeof(WebOkClassContext))]
    partial class WebOkClassContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webOkClass.Models.ReservaSala", b =>
                {
                    b.Property<int>("ReservaSalaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SalaDeAulaId");

                    b.Property<int>("StatusReserva");

                    b.Property<int>("UsuarioId");

                    b.HasKey("ReservaSalaID");

                    b.HasIndex("SalaDeAulaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("reservas");
                });

            modelBuilder.Entity("webOkClass.Models.SalaDeAula", b =>
                {
                    b.Property<int>("SalaDeAulaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumeroDaSala");

                    b.Property<int>("StatusDaSala");

                    b.Property<int>("TipoDeSala");

                    b.HasKey("SalaDeAulaId");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("webOkClass.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Campus");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("TipoFuncionario");

                    b.Property<string>("Token");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("webOkClass.Models.ReservaSala", b =>
                {
                    b.HasOne("webOkClass.Models.SalaDeAula", "SalaDeAula")
                        .WithMany()
                        .HasForeignKey("SalaDeAulaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("webOkClass.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
